import type { Metadata } from "next";
import "./globals.css";
import { Wittgenstein } from 'next/font/google'

const wittgenstein = Wittgenstein({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-wittgenstein',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={wittgenstein.variable}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
